### ISSUE TITLE
JP crashes if there are Thrift transport errors produced by the client

### ISSUE THREAD

**Issue by danharvey** [fredemmott/jp#4]
If the client sends invalid Thrift transport data then it can induce errors in the Thrift service causing jp to crash with an Out Of Sequence error on the client and an 

/usr/lib/ruby/1.9.1/thrift/processor.rb:45:in `skip': don't know how to skip type -128 (NotImplementedError)
        from /usr/lib/ruby/1.9.1/thrift/processor.rb:45:in`read'
        from /usr/lib/ruby/1.9.1/thrift/processor.rb:45:in `read_args'
        from /opt/jp/gen-rb/job_pool.rb:68:in`process_add'
        from /usr/lib/ruby/1.9.1/thrift/processor.rb:29:in `process'
        from /usr/lib/ruby/1.9.1/thrift/server/threaded_server.rb:34:in`block (3 levels) in serve'
        from /usr/lib/ruby/1.9.1/thrift/server/threaded_server.rb:33:in `loop'
        from /usr/lib/ruby/1.9.1/thrift/server/threaded_server.rb:33:in`block (2 levels) in serve'

**Comment by fredemmott** [comment]
Merged a while back, thoguht ticking the box would close the ticket :p

Minor change: cd3e35c
